# 行数
rows: 11

# 列数
cols: 11

# 初始墙数量
initialWallCount: 8

# 游戏范围
# "group": 群内只能开一个游戏, 群内所有人都能玩, key 为群ID
# "user": 每个人都能开一个游戏, 会跨群, key 为用户ID
# "group.user": 每个人都能开一个游戏, 可以在不同的群开多个游戏, key 为群ID+用户ID
scope: "group"

# 发送的图片是否at, at时图片缩略图会变小
at: false

# 没有开始游戏时输入了开始游戏后的指令提示
# false: 不提示直接开始新游戏
noStartTip: "游戏还没开始哦，请输入「#圈小猫」开始游戏吧！"
