# 如果是QQBot一次最多发送 5*10 的按钮

# 行数
rows: 5

# 列数
cols: 10

# 初始等级
level: 0

# 关卡时间
leftTime: 360

# 图案 不能少
design:
  - "▲"
  - "▼"
  - "●"
  - "◆"
  - "■"
  - "★"
  - "▶"
  - "◀"
  - "∈"
  - "∩"
  - "∅"
  - "∑"
  - "☼"
  - "☽"
  - "♀"
  - "♂"
  - "◐"
  - "☑"
  - "☒"
  - "√"
  - "×"
  - "㊣"
  - "卐"
  - "☠"
  - "✈"
  - "☢"
  - "☁"
  - "✪"
  - "卍"
